/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mattcrow.Scheduler;

import java.util.LinkedList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        List<AbstractSchedulingAlgorithm> algs = new LinkedList<>();
        algs.add(new FirstComeFirstServed());
        algs.add(new HighestPriorityFirst());
        for(int q = 1; q <= 5; ++q){
            for(int oh = 0; oh <= q; ++oh){
                algs.add(new RoundRobin(q, oh));
            }
        }
        
        List<Process> processes = InputParser.readProcesses();
        for(Process p : processes){
            System.out.println(p.asTuple());
        }
        System.out.println();
        
        for(AbstractSchedulingAlgorithm alg : algs){
            alg.run(processes);
            System.out.println();
        }
    }
}
