/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toDoList;

import toDoList.gui.GuiLauncher;

public class App {
    public static void main(String[] args) {
        GuiLauncher.launch();
        System.out.println("launching To Do List...");
    }
}
